name       : perl-xml-saxbase
version    : 1.08
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-SAX-Base-1.08.tar.gz : 666270318b15f88b8427e585198abbc19bc2e6ccb36dc4c0a4f2d9807330219e
license    : Artistic-Perl-1.0
summary    : XML::SAX::Base - Base class SAX Drivers and Filters
component  : programming.perl
description: |
    XML::SAX::Base - Base class SAX Drivers and Filters
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
