name       : perl-xml-saxbase
version    : '1.09'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-Base-1.09.tar.gz : 66cb355ba4ef47c10ca738bd35999723644386ac853abbeb5132841f5e8a2ad0
license    : Artistic-1.0-Perl
summary    : XML::SAX::Base - Base class SAX Drivers and Filters
component  : programming.perl
description: |
    XML::SAX::Base - Base class SAX Drivers and Filters
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
